### ISSUE TITLE
Obscured settings for profile checking

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#12]
***Multiple issues***
![image](https://user-images.githubusercontent.com/3089913/46997569-4c0ed800-d120-11e8-9e9f-301542099c99.png)

- Also each profile check should give an indication as to which profile it is.

**Comment by eceozturk** [comment]
Solved in 6af20b8f172de8e94e01481d28587a757d0636b4
