### ISSUE TITLE
Processing indicator is static

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#14]
![image](https://user-images.githubusercontent.com/3089913/46997773-dd7e4a00-d120-11e8-8c5b-a8d13bc6e3cb.png)

Processing indicator is static. No indication of continued activity. Could be a spinner or best case something that updated with the actual progress of the tests.

**Comment by eceozturk** [comment]
Solved in 6af20b8f172de8e94e01481d28587a757d0636b4
