### ISSUE TITLE
Issues with display of test results

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#16]
**Multiple issues**
- The test results are located off to the side – no UI consistency or indication of a linear workflow .
- Results should replace input UI and not be dominated by it. 

![image](https://user-images.githubusercontent.com/3089913/46997916-5c738280-d121-11e8-8d22-85a4aadedd5d.png)

**Comment by eceozturk** [comment]
The results are now moved below the input UI. This is provided in #54
