### ISSUE TITLE
Tree issues

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#17]
- A single click on any of the results items fails
- Users do not know that they need to double-click
- All items show a hand cursor yet not all are clickable.
- Schematron error shows a hand-cursor on mouse-over to indicate a link, but is not clickable
- HbbTV DVB validation error shows shows a hand-cursor on mouse-over to indicate a link, but is not clickable
![image](https://user-images.githubusercontent.com/3089913/46998021-a9efef80-d121-11e8-986a-6efd0276ce91.png)

**Comment by eceozturk** [comment]
The "hand-cursor on mouse-over" issue is addressed in #50 and #51
