### ISSUE TITLE
Log detail window opens in separate page

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#18]
- This breaks the user experience.
- Log results could be shown in a pane of the test window.
![image](https://user-images.githubusercontent.com/3089913/46998065-c5f39100-d121-11e8-93dc-b40b8d2f4227.png)

**Comment by eceozturk** [comment]
Solved in 6af20b8f172de8e94e01481d28587a757d0636b4
