### ISSUE TITLE
Feature list link 

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#19]
- The link to show the feature list is lost and insignificant.
- It should be presented as an output, along with the verification results. 
- Tiny font, no indication of clickability
- Feature list opens in separate page, should be part of same user experience.
![image](https://user-images.githubusercontent.com/3089913/46998150-0521e200-d122-11e8-801b-a39eae07cf40.png)

**Comment by eceozturk** [comment]
This is moved to the results tree in #55 
Opening in separate page can be viewed as a duplicate of #18 
Closing this now.
