### ISSUE TITLE
MPD conformance-only should default to selected

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#20]
- Since most users just want to test the manifest and segment verification takes a long time.
- If the user does not select this, should be some indication of what will take place regarding segment verification. 
- Would be better as a radio button to indicate what the alternate state is
![image](https://user-images.githubusercontent.com/3089913/46998199-271b6480-d122-11e8-89c2-81525305a911.png)

**Comment by eceozturk** [comment]
Solved in 6af20b8f172de8e94e01481d28587a757d0636b4
