### ISSUE TITLE
Further tree issues

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#21]
While a dynamic manifest is being processed, a results tree is shown. Every item shows a hand cursor but nothing is actually clickable until the tests are fully completed, which takes several minutes. 
![image](https://user-images.githubusercontent.com/3089913/46998249-474b2380-d122-11e8-8555-547031aed30a.png)

**Comment by eceozturk** [comment]
This issue is addressed in #50 
Now when hovered over a non-clickable item arrow cursor appears and when hovered over a clickable item hand cursor appears.
