### ISSUE TITLE
Bizarre UI of bitrate issues

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#22]
- Why a huge blue circle and ruled-lines background?
- Totally unconnected design and bizarre UI.
- Needs better and consistent UX along with explanation of what is being tested/estimated.

![image](https://user-images.githubusercontent.com/3089913/46998262-5500a900-d122-11e8-8355-a686e7edaab1.png)

**Comment by eceozturk** [comment]
This is solved with https://github.com/Dash-Industry-Forum/Conformance-Software/pull/410
