### ISSUE TITLE
Confusing interface of bitrate interface

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#23]
- This is reached via a link that says “bitrate estimate”
- Pressing the estimate button results in a “No buffer underrun conformance error detected” message. What happened to the bitrate estimate? 
- Needs much better explanatory text and 

![image](https://user-images.githubusercontent.com/3089913/46998376-a14be900-d122-11e8-8e37-16383b9f4797.png)

**Comment by eceozturk** [comment]
This page is changed in #51, #52 and previously in https://github.com/Dash-Industry-Forum/Conformance-Software/commit/122b437348de3da9c5c71782cf0da2bb8ff6598c 

Now the page UI is changed. 
New features of manual editing and lower value computation are added.
