### ISSUE TITLE
Dynamic timing validation link

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Conformance-Frontend#24]
- Dynamic timing validation link is squeezed in between other items.
- Not clear it is a result
- No explanation of what this is. It is a super-great feature but totally hidden.  
![image](https://user-images.githubusercontent.com/3089913/46998428-cc363d00-d122-11e8-9e7e-a0d460489481.png)

**Comment by eceozturk** [comment]
Solved in 6af20b8f172de8e94e01481d28587a757d0636b4
