### ISSUE TITLE
MPD validation tree incomplete if test is run the second time without reloading the page

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/Conformance-Frontend#44]
Steps to repeat:
 1. Run a conformance test.
2. Upon completion, dont reload the page , only click Go button.

Then the MPD tree doesnt contain Xlink validation, MPD validation and Schematron validation tree elements (log file is shown and it is correct).

**Comment by eceozturk** [comment]
PR #45
