### ISSUE TITLE
Results tree should replace input UI 

### ISSUE THREAD

**Issue by eceozturk** [Dash-Industry-Forum/Conformance-Frontend#56]
Results should replace input UI and not be dominated by it as below.

![tree](https://user-images.githubusercontent.com/35132231/52272473-33ccfe00-2947-11e9-93b4-5b56436c6d14.png)

**Comment by waqarz** [comment]
Remnant from https://github.com/Dash-Industry-Forum/Conformance-Frontend/issues/16

**Comment by eceozturk** [comment]
Solved in 6af20b8f172de8e94e01481d28587a757d0636b4
