### ISSUE TITLE
Profile selection doesn't work in Firefox

### ISSUE THREAD

**Issue by andyburras** [Dash-Industry-Forum/Conformance-Frontend#65]
In Firefox 65.0.1 the profile selection "cog" drop down doesn't appear to drop down.
Does work in Chrome browser.

**Comment by niteeshbhat** [comment]
Fixed here https://github.com/Dash-Industry-Forum/Conformance-Frontend/pull/66

Was working for firefox 66, however now works for firefox 65.0.1 and older versions as well.
