### ISSUE TITLE
validator hangs

### ISSUE THREAD

**Issue by jpiesing** [Dash-Industry-Forum/Conformance-Frontend#72]
The validator hangs with either of the following URLs and when I get the MPD with wget and load it as a file.

http://77.158.55.125/Content/DASH/Live/channel%28cbr%29/manifest.mpd
http://77.158.55.125/Content/DASH/Live/channel%28dash_ll_number%29/manifest.mpd

This happens both with Firefox and Chrome.

**Comment by eceozturk** [comment]
Right now, it seems like the server is down. Currently working on it and will update here once it is up and running.

**Comment by eceozturk** [comment]
Up and running now. If confirmed, this issue can be closed.

**Comment by jpiesing** [comment]
Fine now.
